export const JWT_DEFAULT_SECRET = 'JWT_DEFAULT_SECRET';
export const JWT_VERIFY_EMAIL_SECRET = 'JWT_VERIFY_EMAIL_SECRET';
export const JWT_FORGOT_PASSWORD_SECRET = 'JWT_FORGOT_PASSWORD_SECRET';
export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
